Update getMoexData.yml

diff --git a/.github/workflows/getMoexData.yml b/.github/workflows/getMoexData.yml
--- a/.github/workflows/getMoexData.yml
+++ b/.github/workflows/getMoexData.yml
@@ -47,7 +47,10 @@ jobs:
       run: |
         url="https://iss.moex.com/iss/engines/stock/markets/shares/securities.json?iss.meta=off"
         response_code=$(curl --silent --output data/iss/engines/stock/markets/shares/securities.json "${url}")
-        if [ "${response_code}" -ne 200 ]; then "Request failed with response code: ${response_code}"; fi
+        if [ "${response_code}" -ne 200 ]; then
+          echo "Request failed with response code: ${response_code}"
+          exit 1
+        fi
     - name: DAILY. Get data files from MOEX ISS
       if: ${{ github.event.schedule == '20 00 * * 2-6' }}
       run: |
